// <auto-generated />
using Klassenbibliothek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TodoSuite.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704130000_AddListEmailImportConfigurations")]
    public partial class AddListEmailImportConfigurations
    {
    }
}
